# Change these first
owner: OpenTorc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Marketing Site
    url: https://www.opentorc.com
    maxResponseTime: 10000
    slug: marketing-site
  - name: Platform
    url: https://platform.opentorc.com
    maxResponseTime: 10000
    slug: platform-production
  - name: Platform (Staging)
    url: https://platform-staging.opentorc.com
    maxResponseTime: 10000
    slug: platform-staging
  - name: Platform (Develop)
    url: https://platform-dev.opentorc.com
    maxResponseTime: 10000
    slug: platform-develop
  - name: Search Tool
    url: https://search.opentorc.com
    maxResponseTime: 10000
    slug: search-tool-production
#  - name: Search Tool (Staging)
#    url: https://search-staging.opentorc.com
#    maxResponseTime: 10000
#    slug: search-tool-staging
#  - name: Search Tool (Develop)
#    url: https://search-dev.opentorc.com
#    maxResponseTime: 10000
#    slug: search-tool-develop

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.opentorc.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/90419756
  favicon: https://www.opentorc.com/favicon-32x32.png
  name: Upptime
  introTitle: "**Torc Status**: This is the status of the Torc platform"
  introMessage: Torc Platform Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Feedback
      href: https://github.com/opentorc/feedback
    - title: Torc
      href: https://www.opentorc.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 5 * * *"
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
